apache:
    container_name: php-apache
    image: ruslangetmansky/docker-apache-php:7.0
    volumes:
      - .:/var/www/app
    environment:
      - APACHE_DOC_ROOT=/var/www/app/public
    links:
    - mysql
    ports:
    - "8080:80"
    privileged: true

mysql:
    image: mysql:latest
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: passroot
        MYSQL_DATABSE: rest_api
        MYSQL_USER: root


